### ISSUE TITLE
Crumbs not outputting at all

### ISSUE THREAD

**Issue by melcarthus** [Log1x/crumb#10]
I have added this packed to my sage 10 site and I can't get the breadcrumbs to display.

Is this outdated? there are also deprecation error for use Roots\Acorn\ServiceProvider;
if I use use Roots\Acorn\Sage\SageServiceProvider it goes away.

Also ```return Crumb::build()->toArray();``` throws an Undefined Type. but this goes away if I use SageServiceProvider.

Does this need an update or is there a new/better way to get breadcrumbs for sage that I don't know about?

**Comment by Log1x** [comment]
A PR would be appreciated for the deprecation warning, otherwise, the package does work and I use it on a couple Sage/Acorn sites running the latest Acorn. I'm using it exactly like the README shows with the addition of a `is_single()` check on the `item()` method.

**Comment by melcarthus** [comment]
Good to know, 

I'll test it again on a new project. Maybe there is something wrong with the theme I'm currently working on then.
