### ISSUE TITLE
Crumbs not working on tax

### ISSUE THREAD

**Issue by mateuszswol** [Log1x/crumb#15]
I want to use Crumb on taxonomy page and I encountered error: `Attempt to read property "term_id" on bool`.

I found an issue in https://github.com/Log1x/crumb/blob/52d99c71241dbe672aadb964f0a33a2255393275/src/Crumb.php#L164. 

We should use `name` instead of `title` in `get_term_by()`.

**Comment by Log1x** [comment]
hey good catch. want to submit a PR? otherwise I will push a release tonight.
