### ISSUE TITLE
PHP Deprecated:  Creation of dynamic property

### ISSUE THREAD

**Issue by iign** [Log1x/crumb#20]
I'm getting this warning using Crumb v1.1.3 & PHP 8.2.10:

`PHP Deprecated:  Creation of dynamic property Log1x\Crumb\Crumb::$config is deprecated in [...]vendor/log1x/crumb/src/Crumb.php on line 25`

btw, thanks for your work on WP, ACF & Sage, just sent a small amount to support that.

**Comment by Log1x** [comment]
should be fixed in 1.1.4.

thanks for the support :)
