### ISSUE TITLE
Installation in sage / bedrock ?

### ISSUE THREAD

**Issue by Specialistinwebsites** [Log1x/crumb#5]
Apologies in advance for any misunderstandings. I'm trying to install this to my Sage10 app, but can't seem to get it to work. 

Installing it to sage gives me the option to release the config file, but gives a "base_path" error. 

`Call to undefined function Illuminate\Foundation\Console\base_path()`

Installing it to bedrock lets phpstorm recognize the class "Log1x\Crumb\Facades\Crumb;" in "View/Components/Breadcrumb.php", but gives an error when compiling;

`Class 'Crumb' not found`

Any help would be appriciated!

**Comment by Log1x** [comment]
This should work without any issues on the latest version of Acorn.

**Comment by slackday** [comment]
Acorn 2.0.5 seems to be the latest version right now and it gives the same error. What causes it?

**Comment by turpoint** [comment]
Before publishing the CrumbServiceProvider, run `wp acorn optimize:clear`. Worked for me.
